### ISSUE TITLE
"ProtonMail - remove forced signature" userscript not working on beta.protonmail.com

### ISSUE THREAD

**Issue by anon88391** [darkred/Userscripts#13]
When using the userscript with Violentmonkey or Greasemonkey (didn't test with Tampermonkey) on the latest Firefox 83.0 injection fails and the console returns the following error

`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).`

Is there any modification you could make to the script to make it work again?

**Comment by darkred** [comment]
> The scripts are tested to work with Tampermonkey and Violentmonkey.
> Greasemonkey -any version- is not supported.

And, I just tested again and the script works fine in both TM and VM.

**Comment by anon88391** [comment]
> And, I just tested again and the script works fine in both TM and VM.

It appears it works on mail.protonmail.com but not on beta.protonmail.com. Could you verify this?

**Comment by darkred** [comment]
No need to open a second issue. Please be more patient.

---

Yes, it doesn't work, because in the beta version the signature element now gets created after the iframe is created. Therefore the arrivejs doesn't help.

I filed this issue https://github.com/kylekyle/monitoring/issues/3 hopefully.
I'll keep trying to find a solution in the meantime.
*I'm always open for PR of course!*

**Comment by darkred** [comment]
Fixed in new version.

**Comment by anon88391** [comment]
The update doesn't seem to fix beta.protonmail.com for me, the signature still doesn't get deleted. I'm using latest Firefox 83.0 with Violentmonkey.

**Comment by darkred** [comment]
In Chrome it works fine with TM/VM.
You are right about Firefox, I'll see what I can do.

**Comment by darkred** [comment]
I believe that Firefox no longer allows to do that.
I describe my efforts in my two posts below:
- [GreasyFork Forum - mutationObserver on iframe doesn't seem to work in Firefox (ok in Chrome)](https://stackoverflow.com/questions/65099471/mutationobserver-on-iframe-works-ok-in-chrome-but-not-in-firefox)
- [Stackoverflow - mutationObserver on iframe works ok in Chrome, but not in Firefox](https://greasyfork.org/en/discussions/development/68347-mutationobserver-inside-iframe-doesn-t-seem-to-work-with-tampermonkey-violentmonkey-in-firefox-ok-in-chrome)

**Comment by darkred** [comment]
After the recent layout update, there's no `beta` subdomain (beta.protonmail.com) anymore.
See https://github.com/darkred/Userscripts/issues/27#issuecomment-857140170
